version: '3'
services:
  web:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - NODE_ENV=development
    command: npm run dev
    volumes:
      - .:/opt/app/
    ports:
      - '4000:3000'
    restart: always
    environment:
      - NODE_ENV=development
x